### ISSUE TITLE
Incidencia en consultas XPath

### ISSUE THREAD

**Issue by piruina** [OscarMaestre/JXMLTool#1]
Hola Óscar, por si te sirve de ayuda sobre lo que te he comentado esta tarde.
La clase javax.xml.transform en su método .transform() utiliza la clase DOM2TO, esta clase en la línea 113 ignora los nodos de tipo atributo, por lo que las consultas de XPath que devuelvan un nodo atributo serán ignoradas.
Ejemplo de consulta xpath "/inventario/producto/peso/@unidad"

private void parse(Node node)
       throws IOException, SAXException
   {
       if (node == null) return;
       switch (node.getNodeType()) {
       **case Node.ATTRIBUTE_NODE:**         // handled by ELEMENT_NODE
       case Node.DOCUMENT_TYPE_NODE :
       case Node.ENTITY_NODE :
       case Node.ENTITY_REFERENCE_NODE:
       case Node.NOTATION_NODE :
           // These node types are ignored!!!
           break;
       case Node.CDATA_SECTION_NODE:
           _handler.startCDATA();
           _handler.characters(node.getNodeValue());
           _handler.endCDATA();
           break;
...

No sé si esta pueda ser la causa del problema.
Un saludo!

**Comment by OscarMaestre** [comment]
Hola:

Gracias pero no, ese codigo es de la propia plataforma Java y funciona perfectamente. El problema estaba en mi código, que daba por sentado que lo que se recupera siempre son elementos XML. El resultado de una consulta podrían ser también nodos texto, cosa que no había contemplado.

Un saludo
